repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0  # Use the latest version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-docstring-first

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.8.0  # Use the latest version
    hooks:
      - id: isort
